### ISSUE TITLE
Implement PartShop endpoints

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL2#239] opened 2020-05-18 18:15 UTC
There are a number of new SBH endpoints -- including some that were never implemented in the original pySBOL.

First step should be to go through the SBH http API documentation and create an issue for each endpoint:

See https://synbiohub.github.io/api-docs/#user-endpoints

**Comment by jakebeal** [comment] 2020-05-20 13:26
Duplicate of #180

**Closed by jakebeal** 2020-05-20 13:26 UTC
Labels: duplicate
